# Generated by Django 6.0.3 on 2026-03-10 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='symbols.symbol')),
                ('symbol_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='symbols.symbol')),
                ('symbol_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='symbols.symbol')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.gamesession')),
            ],
        ),
    ]
