# Generated by Django 6.0.3 on 2026-03-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player_name',
            field=models.CharField(default='Anônimo', max_length=150),
        ),
    ]
