# Generated by Django 6.0.3 on 2026-03-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='credits',
            field=models.IntegerField(default=100),
        ),
    ]
