# Generated by Django 6.0.3 on 2026-03-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='credits',
            new_name='balance',
        ),
    ]
